<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/1st_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N o`lchamli massiv(array) larga ishlov berish

In [ ]:
import numpy as np

In [ ]:
data1=[1.4,2,4,7] # list
arr1=np.array(data1)

In [ ]:
arr1

array([1.4, 2. , 4. , 7. ])

In [ ]:
data2=(2,3.5,6,9) # tuple
arr2=np.array(data2)

In [ ]:
arr2

array([2. , 3.5, 6. , 9. ])

Massiv o`lchami
.nidm

In [ ]:
arr1.ndim # array1 ning o`lchami

1

In [ ]:
arr2.ndim # array2 ning o`lchami

1

2 va undan ortiq massivlar

In [ ]:
data3=[[1,2,3,4],[4,6,7,8]] # nested list
arr3=np.array(data3)

In [ ]:
arr3.ndim

2

In [ ]:
data4=[[[[1,2]],[[3,4]]]]
arr4=np.array(data4)

In [ ]:
arr4.ndim

4

In [ ]:
arr4

array([[[[1, 2]],

        [[3, 4]]]])

shape, size methods

In [ ]:
arr3

array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

zeros and ones functions

In [ ]:
arr5=np.zeros((2,4))

In [ ]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6=np.ones((2,4))

In [ ]:
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arange function

In [ ]:
arr7=np.arange(2,24,3)

In [ ]:
arr7

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [ ]:
arr8=np.arange(15)

In [ ]:
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:

def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  data=list(range(n))
  arr=np.array(data)
  return arr

In [ ]:
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    data1=[]
    data2=[]
    data3=[data1,data2]
    arr=np.array(data3)
    arr=np.random.rand(r,c)
    return arr
