![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum
Maʼlumotlar tahlili. Numpy kutubxonasi.

8.20. Fayllar bilan ishlash

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)

In [ ]:
np.save('data', arr)

In [ ]:
arr2= np.load('data.npy')

In [ ]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(20)

In [ ]:
np.savez('arrays',a=arr, b=arr1)

In [ ]:
arrays = np.load('arrays.npz')

In [ ]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)