<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/_4_boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
names=np.array(['Hasan','Husan','Mirzabek','Elyor','Hasan','Jvaohir','Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Jvaohir', 'Elyor'],
      dtype='<U8')

In [4]:
data=np.random.randn(7,4)
data

array([[-0.48215174,  0.06783732,  0.3230539 ,  0.77447255],
       [ 0.67241501, -0.66489328,  2.29953114,  0.46382451],
       [ 0.65559634, -0.3490481 , -0.64484948, -2.39579594],
       [-0.33965435, -0.35768009,  2.78800715, -1.72941529],
       [-0.80126359, -0.06189583,  0.35733987,  1.21505393],
       [ 0.31447608, -0.80898165,  0.06885335,  0.38765859],
       [-0.23835702,  0.83254879, -0.09829183, -0.34513402]])

In [5]:
names=='Hasan'

array([ True, False, False, False,  True, False, False])

In [6]:
data[names=='Hasan']

array([[-0.48215174,  0.06783732,  0.3230539 ,  0.77447255],
       [-0.80126359, -0.06189583,  0.35733987,  1.21505393]])

In [7]:
data[names=='Elyor']

array([[-0.33965435, -0.35768009,  2.78800715, -1.72941529],
       [-0.23835702,  0.83254879, -0.09829183, -0.34513402]])

In [8]:
data[names=='Mirzabek']

array([[ 0.65559634, -0.3490481 , -0.64484948, -2.39579594]])

In [9]:
data[names=='Mirzabek',1:2]

array([[-0.3490481]])

In [10]:
data[names!='Hasan']

array([[ 0.67241501, -0.66489328,  2.29953114,  0.46382451],
       [ 0.65559634, -0.3490481 , -0.64484948, -2.39579594],
       [-0.33965435, -0.35768009,  2.78800715, -1.72941529],
       [ 0.31447608, -0.80898165,  0.06885335,  0.38765859],
       [-0.23835702,  0.83254879, -0.09829183, -0.34513402]])

In [11]:
data[~(names=='Hasan')]

array([[ 0.67241501, -0.66489328,  2.29953114,  0.46382451],
       [ 0.65559634, -0.3490481 , -0.64484948, -2.39579594],
       [-0.33965435, -0.35768009,  2.78800715, -1.72941529],
       [ 0.31447608, -0.80898165,  0.06885335,  0.38765859],
       [-0.23835702,  0.83254879, -0.09829183, -0.34513402]])

In [13]:
mask=(names=='Hasan') | (names=='Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [14]:
data[mask]

array([[-0.48215174,  0.06783732,  0.3230539 ,  0.77447255],
       [ 0.67241501, -0.66489328,  2.29953114,  0.46382451],
       [-0.80126359, -0.06189583,  0.35733987,  1.21505393]])

In [15]:
data

array([[-0.48215174,  0.06783732,  0.3230539 ,  0.77447255],
       [ 0.67241501, -0.66489328,  2.29953114,  0.46382451],
       [ 0.65559634, -0.3490481 , -0.64484948, -2.39579594],
       [-0.33965435, -0.35768009,  2.78800715, -1.72941529],
       [-0.80126359, -0.06189583,  0.35733987,  1.21505393],
       [ 0.31447608, -0.80898165,  0.06885335,  0.38765859],
       [-0.23835702,  0.83254879, -0.09829183, -0.34513402]])

In [16]:
data[data<0]=0
data

array([[0.        , 0.06783732, 0.3230539 , 0.77447255],
       [0.67241501, 0.        , 2.29953114, 0.46382451],
       [0.65559634, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.78800715, 0.        ],
       [0.        , 0.        , 0.35733987, 1.21505393],
       [0.31447608, 0.        , 0.06885335, 0.38765859],
       [0.        , 0.83254879, 0.        , 0.        ]])