<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/_5_Transpsing%26Swappinh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Massivlar positsiyasini ko'chirish `Transpose` va o'qlar o'rnini almashtirish `Swapping axes`
`reshape`

In [4]:
A=np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.T # Transposing A


array([[0, 2, 4],
       [1, 3, 5]])

`swaping axe`

In [10]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [17]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [19]:
np.dot(A,A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])