<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Massivlarga malumot turini aniq kiritish,malumot turlarini aniqlash,malumot turini o`zgartirish

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4], dtype=np.float64)
arr1

array([1., 2., 3., 4.])

In [ ]:
arr2=np.array([4,5,8,9], dtype=np.int32)
arr2

array([4, 5, 8, 9], dtype=int32)

`dtype` method

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

Changing type of data
`astype` method

In [ ]:
arr3=np.array([1,2,3,4])
arr3.dtype

dtype('int64')

In [ ]:
arr4=arr3.astype(np.float64)


In [ ]:
arr4.dtype

dtype('float64')

In [ ]:
data=np.array([1.2,4.5,2.0,8.9])
data.dtype

dtype('float64')

In [ ]:
int_data=data.astype(np.int64)
int_data

array([1, 4, 2, 8])

In [ ]:
int_data.dtype

dtype('int64')