<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data=np.arange(10,100,10)
data

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
data[4]

np.int64(50)

In [ ]:
data[2:6]

array([30, 40, 50, 60])

Massivning kesib olingan qismiga o'zgartish kiritilsa, asosiy manba massivga tasir qiladi

In [ ]:
sliced_data=data[3:5]
sliced_data[:]=0
data

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

`copy`

In [ ]:
arr1=np.arange(10,100,10)

In [ ]:
sliced_arr=arr1[3:7].copy()
sliced_arr[:]=0
sliced_arr

array([0, 0, 0, 0])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2 olchamli massiv indekslari

In [ ]:
arr2=np.array([[1,2,3],[5,6,7],[8,9,10]])
arr2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
arr2[2,0]

np.int64(8)

In [ ]:
arr2[0,2]

np.int64(3)

2-o`lchamli massivlarni kesish

In [ ]:
sl_arr=arr2[1, :2]
sl_arr

array([5, 6])

3-o'lchamli massivlarda index va slicing

In [ ]:
arr3d=np.array([[[1,2,3,4],
               [4,6,7,8],
               [9,10,11,12]],

                [[13,14,15,16],
                [17,18,19,20],
                [21,22,23,24]],

                [[25,26,27,28],
                [29,30,31,32],
                [33,34,35,36]]])


In [ ]:
arr3d[0][2,1:]

array([10, 11, 12])

In [ ]:
arr3d[1][1,:3]

array([17, 18, 19])

In [ ]:
arr3d[2][2,2]

np.int64(35)