<a href="https://colab.research.google.com/github/smdr111/Numpy_roadmap/blob/main/NUMPY_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [ ]:
numbers=list(range(10))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr_numbers=np.array(numbers)
arr_numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_numbers.ndim

1

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz oʻlchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr=np.zeros((1,1,1,1,1,1,1,1,1))
arr

array([[[[[[[[[0.]]]]]]]]])

In [ ]:
arr.ndim

9

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr1=np.random.randn(3,6)
arr1

array([[-0.96263539,  2.74778662,  0.69007268,  1.8667648 ,  0.1884644 ,
        -0.24162051],
       [ 0.04232052,  0.52913477,  1.95983148,  0.89379254, -0.05595353,
         0.47400035],
       [-0.52557701, -1.28882221, -0.57403536, -2.287373  , -0.59213157,
         0.28856216]])

In [ ]:
arr1.itemsize

8

#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
np.add??

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [ ]:
arr2=np.zeros((12))
arr2[5]=1
arr2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr3=np.arange(20,59)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [ ]:
arr3[::-1]


array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr4=np.arange(12,21).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr5=np.array([3, 7, 0, 0, 9, 0])
arr5.nonzero()

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr6=np.random.random(8).reshape(2,2,2)
arr6

array([[[0.81958397, 0.76478741],
        [0.28669207, 0.4886009 ]],

       [[0.70569015, 0.52804496],
        [0.87365003, 0.05142205]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [ ]:
arr7=np.random.random(81).reshape(9,9)
arr7

array([[0.12242345, 0.104185  , 0.95932758, 0.8729979 , 0.26118   ,
        0.83973049, 0.04601278, 0.47028949, 0.47931477],
       [0.78471385, 0.6313211 , 0.85388338, 0.56920696, 0.74918599,
        0.08518289, 0.58711448, 0.20138079, 0.04410999],
       [0.03396797, 0.09739433, 0.65217526, 0.32275301, 0.73803596,
        0.5123123 , 0.64013682, 0.83387647, 0.3157572 ],
       [0.12388335, 0.40312957, 0.82755009, 0.81480507, 0.76565134,
        0.52461948, 0.8171736 , 0.20592269, 0.40883946],
       [0.71430235, 0.1334696 , 0.54058116, 0.07336855, 0.05131996,
        0.21852516, 0.98463727, 0.83527912, 0.96998826],
       [0.94432704, 0.27870602, 0.44082406, 0.01675045, 0.47309557,
        0.89325515, 0.04052315, 0.01139839, 0.07071634],
       [0.26745695, 0.44715782, 0.16648748, 0.01216125, 0.18831974,
        0.88894679, 0.4347538 , 0.53454949, 0.14596647],
       [0.76478528, 0.48983836, 0.83647398, 0.58464593, 0.55828239,
        0.29148801, 0.55220219, 0.86151313, 0.92095389],


In [ ]:
arr7.min()

np.float64(0.011398391262236518)

In [ ]:
arr7.max()

np.float64(0.9846372680998169)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan -> nan
np.nan == np.nan -> False
np.inf > np.nan -> False
np.nan - np.nan = nan
np.nan in set([np.nan]) -> False
0.7 == 7 * 0.1 -> False
```


`💡Ishora` NaN = not a number, inf = infinity

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
x=np.arange(18).reshape(6,3)
y=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.dot(x,y)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a=np.array([1,2])
b=np.array([4,5])
a>b

array([False, False])

In [ ]:
a>=b

array([False, False])

In [ ]:
a<b

array([ True,  True])

In [ ]:
a<=b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [ ]:
a=np.arange(1,20,3)
b=np.arange(1,20)
np.intersect1d(a,b)

array([ 1,  4,  7, 10, 13, 16, 19])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
array=np.random.randn(2,4)
array

array([[ 1.7961592 , -0.40958955, -0.73471878,  0.27623242],
       [ 1.93975768, -0.00973355, -0.81548717,  0.79021153]])

In [ ]:
array[array>0].astype(int)

array([1, 0, 1, 0])

In [ ]:
array[array>0]-(array[array>0]%1)

array([1., 0., 1., 0.])

In [ ]:
np.floor(array[array>0])

array([1., 0., 1., 0.])

In [ ]:
np.trunc(array[array>0])

array([1., 0., 1., 0.])

#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [ ]:
arr8=np.random.randint(3,size=(3,3))
arr8

array([[1, 1, 2],
       [2, 2, 1],
       [2, 0, 1]])

In [ ]:
arr9=np.tile(np.arange(3),3).reshape(3,3)
arr9

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr10=np.random.random(10)
arr10

array([0.33080562, 0.48194669, 0.90029164, 0.93346315, 0.87712213,
       0.43961106, 0.70208228, 0.05860025, 0.07681527, 0.69159405])

In [ ]:
arr10.sort()
arr10

array([0.05860025, 0.07681527, 0.33080562, 0.43961106, 0.48194669,
       0.69159405, 0.70208228, 0.87712213, 0.90029164, 0.93346315])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A=np.random.random(10)
B=np.random.random(10)
A

array([0.55355145, 0.79216454, 0.21460597, 0.69545603, 0.76631762,
       0.17209301, 0.04000267, 0.97142329, 0.00841945, 0.13167888])

In [ ]:
B

array([0.49333671, 0.81084335, 0.65400292, 0.65952349, 0.03210321,
       0.16323664, 0.96237936, 0.05689062, 0.2036175 , 0.33415873])

In [ ]:
np.allclose(A,B)

False

In [ ]:
np.array_equal(A,B)

False

#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
x=np.arange(18).reshape(6,3)
y=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x.dot(y)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [ ]:
arr11=np.random.random(5)
arr11

array([0.78532422, 0.2240453 , 0.0059606 , 0.49150311, 0.87009627])

In [ ]:
max_index=np.argmax(arr11)

In [ ]:
arr11[max_index]=0
arr11

array([0.78532422, 0.2240453 , 0.0059606 , 0.49150311, 0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
today=np.datetime64('today')
yesterday=today-np.timedelta64(1,'D')
yesterday

np.datetime64('2025-08-03')

In [ ]:
tomorrow=today+np.timedelta64(1,'D')
tomorrow

np.datetime64('2025-08-05')

#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [31]:
dates=np.arange('2016-01-01','2016-02-01',dtype='datetime64[D]')
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
# this problem is given secon time

#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [33]:
arr12=np.arange(10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.sum(arr12)

np.int64(45)

In [35]:
np.add.reduce(arr12)

np.int64(45)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [48]:
arr14=np.array([1, 2, 3, 4, 5])
result=np.zeros(len(arr14)*4-3,dtype=int)
result[::4]=arr14
result

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [53]:
a=np.arange(1,15)
np.lib.stride_tricks.as_strided(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [64]:
arr15=np.array([1,2,2,2,3,4,5,6,3,1,1,5,8,9,11,12,11,16,6])
count=np.bincount(arr15)
most_common=np.argmax(count)
most_common


np.int64(1)

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`